apiVersion: v1
kind: Service
metadata:
  labels:
    app: rack-app-service
  name: rack-app-service
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: rackapp
  type: NodePort
